
@baseUrl=http://localhost:4004

###Do a GET call for the table

GET {{baseUrl}}/ADM_srv/TB_USER_PROFILE?$expand=SubAccountAccess,SpaceAccess,AssignedRoleCollections


### Create a new user profile with nested compositions
POST {{baseUrl}}/ADM_srv/TB_USER_PROFILE
Content-Type: application/json

{
  "USER_PID": "P12345678",
  "USER_EMAIL_ID": "subhampani@yahoo.com",
  "STATUS": "ACTIVE",
  "SubAccountAccess": [
    { "SUBACCOUNT_VALUE": "DEV" },
    { "SUBACCOUNT_VALUE": "Dev_Test" }
  ],
  "SpaceAccess": [
    { "SPACE_VALUE": "SPACE1_TEST" },
    { "SPACE_VALUE": "SPACE2_TEST" }
  ],
  "AssignedRoleCollections": [
    { "ROLE_COLLECTION_VALUE": "BAS Developer" },
    { "ROLE_COLLECTION_VALUE": "Destination developer" }
  ]
}

###
# Function call getSubaccounts()
# @name getSubaccounts_function_GET
GET {{baseUrl}}/ADM_srv/getSubaccounts()

###

@subAccountId={{getSubaccounts_function_GET.response.body.$.value[0].subaccountId}}

###
# Function call getSpaces()
# @name getSpaces_function_GET
GET {{baseUrl}}/ADM_srv/getSpaces()

######

POST {{baseUrl}}/GetSpacedata/getSpacesFromSubaccount
Content-Type: application/json

{
  "subaccountId": "43c9bb1f-d5e6-4c25-af7a-4888e40026d4"
}