
@baseUrl=http://localhost:4004

###Do a GET call for the table

GET {{baseUrl}}/ADM_srv/TB_USER_PROFILE?$expand=SubAccountAccess,SpaceAccess,AssignedRoleCollections


### Create a new user profile with nested compositions
POST {{baseUrl}}/ADM_srv/TB_USER_PROFILE
Content-Type: application/json

{
  "USER_PID": "P12345678",
  "USER_EMAIL_ID": "subhampani@yahoo.com",
  "STATUS": "ACTIVE",
  "SubAccountAccess": [
    { "SUBACCOUNT_VALUE": "DEV" },
    { "SUBACCOUNT_VALUE": "Dev_Test" }
  ],
  "SpaceAccess": [
    { "SPACE_VALUE": "SPACE1_TEST" },
    { "SPACE_VALUE": "SPACE2_TEST" }
  ],
  "AssignedRoleCollections": [
    { "ROLE_COLLECTION_VALUE": "BAS Developer" },
    { "ROLE_COLLECTION_VALUE": "Destination developer" }
  ]
}

###
# Function call getSubaccounts()
# @name getSubaccounts_function_GET
GET {{baseUrl}}/ADM_srv/getSubaccounts()

###

@subAccountId={{getSubaccounts_function_GET.response.body.$.value[0].subaccountId}}

###
# Function call getSpaces()
# @name getSpaces_function_GET
GET {{baseUrl}}/ADM_srv/getSpaces()

######

GET {{baseUrl}}/GetSpacedata/getSpacesFromSubaccount
Content-Type: application/json

{
  "subaccountId": "43c9bb1f-d5e6-4c25-af7a-4888e40026d4"
}


### Create a New User
POST{{baseUrl}}/user-management-service/CreateUser
Content-Type: application/json

{
  "userName": "john.doe",
  "emails": [
    { "value": "john.doe@example.com", "type": "work" }
  ],
  "roles": [
    "MyRoleCollection"
  ]
}

###

### Get All Users
GET {{baseUrl}}/user-management-service/GetUsers

###

### Update User
POST {{baseUrl}}/user-management-service/UpdateUser
Content-Type: application/json

{
  "ID": "replace-with-user-id",
  "userName": "john.doe",
  "emails": [
    { "value": "john.doe@newdomain.com", "type": "work" }
  ],
  "roles": [
    "UpdatedRoleCollection"
  ]
}

###

### Delete User
POST {{baseUrl}}/user-management-service/DeleteUser
Content-Type: application/json

{
  "ID": "replace-with-user-id"
}

#####

POST {{baseUrl}}/Sapce_srv/AssignSpaceDeveloper
Content-Type: application/json

{
  "data": {
    "userGUID": "0f1582b8-514c-45f6-b110-00ae1ea2bc31",
    "spaceGUID": "34e33b2b-a2aa-4003-a485-d56267659b22"
  }
}

### Get user GUID by email
POST http://localhost:4004/Lookup_srv/GetUserGUIDByEmail
Content-Type: application/json

{
  "data": {
    "userName": "subhampani1313@gmail.com",
    "origin": "sap.default"
  }
}